### ISSUE TITLE
Lua Error that keeps coming up

### ISSUE THREAD

**Issue by Auxiliotest** [liquidbase/DuffedUIv9#1]
Message: ...rface\AddOns\DuffedUI\modules\actionbars\extraAB.lua:24: attempt to index field 'Backdrop' (a nil value)
Time: Fri Aug 14 19:11:32 2020
Count: 7
Stack: ...rface\AddOns\DuffedUI\modules\actionbars\extraAB.lua:24: attempt to index field 'Backdrop' (a nil value)
[string "@Interface\AddOns\DuffedUI\modules\actionbars\extraAB.lua"]:24: in function <...rface\AddOns\DuffedUI\modules\actionbars\extraAB.lua:19>
[string "=[C]"]: in function `UpdateDisplayedZoneAbilities'
[string "@Interface\FrameXML\ZoneAbility.lua"]:65: in function <Interface\FrameXML\ZoneAbility.lua:64>

Locals: self = ZoneAbilityFrame {
 0 = <userdata>
 SpellButtonContainer = <unnamed> {
 }
 Style = <unnamed> {
 }
 UpdateDisplayedZoneAbilities = <function> defined =[C]:-1
 CheckForTutorial = <function> defined @Interface\FrameXML\ZoneAbility.lua:128
 layoutIndex = 1
 OnLoad = <function> defined @Interface\FrameXML\ZoneAbility.lua:53
 OnEvent = <function> defined @Interface\FrameXML\ZoneAbility.lua:64
}
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
  = true
  = true
}
(for control) = <unnamed> {
 0 = <userdata>
 OnEnter = <function> defined @Interface\FrameXML\ZoneAbility.lua:159
 CheckForTutorial = <function> defined @Interface\FrameXML\ZoneAbility.lua:204
 layoutIndex = 2
 OnDragStart = <function> defined @Interface\FrameXML\ZoneAbility.lua:172
 Icon = <unnamed> {
 }
 OnClick = <function> defined @Interface\FrameXML\ZoneAbility.lua:168
 SetSpellID = <function> defined @Interface\FrameXML\ZoneAbility.lua:208
 hover = frame {
 }
 pushed = frame {
 }
 OnShow = <function> defined @Interface\FrameXML\ZoneAbility.lua:147
 OnLoad = <function> defined @Interface\FrameXML\ZoneAbility.lua:143
 GetSpellID = <function> defined @Interface\FrameXML\ZoneAbility.lua:217
 Refresh = <function> defined @Interface\FrameXML\ZoneAbility.lua:178
 backdrop = <unnamed> {
 }
 OnEvent = <function> defined @Interface\FrameXML\ZoneAbility.lua:155
 NormalTexture = <unnamed> {
 }
 SetContent = <function> defined @Interface\FrameXML\ZoneAbility.lua:221
 Count = <unnamed> {
 }
 zoneAbilityInfo = <table> {
 }
 OnLeave = <function> defined @Interface\FrameXML\ZoneAbility.lua:164
 OnHide = <function> defined @Interface\FrameXML\ZoneAbility.lua:151
 Cooldown = <unnamed> {
 }
 spellID = 326526
}
SpellButton = <unnamed> {
 0 = <userdata>
 OnEnter = <function> defined @Interface\FrameXML\ZoneAbility.lua:159
 CheckForTutorial = <function> defined @Interface\FrameXML\ZoneAbility.lua:204
 layoutIndex = 2
 OnDragStart = <function> defined @Interface\FrameXML\ZoneAbility.lua:172
 Icon = <unnamed> {
 }
 OnClick = <function> defined @Interface\FrameXML\ZoneAbility.lua:168
 SetSpellID = <function> defined @Interface\FrameXML\ZoneAbility.lua:208
 hover = frame {
 }
 pushed = frame {
 }
 OnShow = <function> defined @Interface\FrameXML\ZoneAbility.lua:147
 OnLoad = <function> defined @Interface\FrameXML\ZoneAbility.lua:143
 GetSpellID = <function> defined @Interface\FrameXML\ZoneAbility.lua:217
 Refresh = <function> defined @Interface\FrameXML\ZoneAbility.lua:178
 backdrop = <unnamed> {
 }
 OnEvent = <function> defined @Interface\FrameXML\ZoneAbility.lua:155
 NormalTexture = <unnamed> {
 }
 SetContent = <function> defined @Interface\FrameXML\ZoneAbility.lua:221
 Count = <unnamed> {
 }
 zoneAbilityInfo = <table> {
 }
 OnLeave = <function> defined @Interface\FrameXML\ZoneAbility.lua:164
 OnHide = <function> defined @Interface\FrameXML\ZoneAbility.lua:151
 Cooldown = <unnamed> {
 }
 spellID = 326526
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = <unnamed> {
 0 = <userdata>
 OnEnter = <function> defined @Interface\FrameXML\ZoneAbility.lua:159
 CheckForTutorial = <function> defined @Interface\FrameXML\ZoneAbility.lua:204
 layoutIndex = 2
 OnDragStart = <function> defined @Interface\FrameXML\ZoneAbility.lua:172
 Icon = <unnamed> {
 }
 OnClick = <function> defined @Interface\FrameXML\ZoneAbility.lua:168
 SetSpellID = <function> defined @Interface\FrameXML\ZoneAb

**Comment by Auxiliotest** [comment]
Count 82 and rising :)

**Comment by liquidbase** [comment]
Jips that normal if the button is for a quest permanently present. Issue will be fixed in a few seconds here on GitHub

**Comment by liquidbase** [comment]
Fix is there. Please check of the issue persist

**Comment by Auxiliotest** [comment]
Seem to be working fine now, I did how ever get this error on login but has not returned yet though, dunno if it was a one off or not :)

Message: Usage: local success = C_ChatInfo.SendAddonMessage(params)
Time: Fri Aug 14 20:30:39 2020
Count: 5
Stack: Usage: local success = C_ChatInfo.SendAddonMessage(params)
[string "=[C]"]: ?
[string "=[C]"]: in function `SendAddonMessage'
[string "@Interface\AddOns\DuffedUI\core\cversion.lua"]:42: in function <Interface\AddOns\DuffedUI\core\cversion.lua:23>

Locals: (*temporary) = "Usage: local success = C_ChatInfo.SendAddonMessage(params)"

**Comment by Auxiliotest** [comment]
And Thanks for the fast action @liquidbase :)

**Comment by liquidbase** [comment]
You're welcome :)
The problem with the version check is strange here because the code is correct in itself. I'm currently looking for a solution.

**Comment by liquidbase** [comment]
Okay I have deployed on Github a attempt to fix the versioncheck.

**Comment by Auxiliotest** [comment]
Ok will try it out

**Comment by Auxiliotest** [comment]
Servers seem offline right now, but will try ASAP. Meanwhile I have a question, where do you see when you enter a "Rest area", I can't seem to find the Zzz or similar anywhere :)

**Comment by Auxiliotest** [comment]
A bit wierd, I can log in but every time the Duffed Splash screen shows up I get disconnected. No LUA errors showing though.

**Comment by Auxiliotest** [comment]
Logged in with Duffed disabled and then activated and reloaded in game, works fine now and no errors so far. Not sure if the previous dc was related to server issues or the addon. Will try to log out and in with addon enabled again to see if i can reproduce the disconnect again.

**Comment by Auxiliotest** [comment]
All good now, logged in with the UI enabled and no errors, will do some questing and report back again later. Thanks again for a great addon and excellent service 🥇

**Comment by Auxiliotest** [comment]
Ok Have been playing for a while now. No new errors so all seem good, Thx again 💯

**Comment by liquidbase** [comment]
Your Welcome :)
Resting can be tracked on the left chatpanel on the experiencebar. If you are in a resting area there will appear the Zzz-Symbol. 
Disconnect issues are currently server based

**Comment by Auxiliotest** [comment]
Thanks again :)
