### ISSUE TITLE
WowB Fatal exception when DuffedUI is enabled

### ISSUE THREAD

**Issue by Auxiliotest** [liquidbase/DuffedUIv9#15]
Hey it's me again :)

Since yesterday whenever I try to start Shadowlands Beta with DuffedUI enabled i can't even get in the game without crashing. Please see attached screen capture of the error itself. This does not happen when I disable DuffedUI, nor does it happen if I try other UI's, but I like yours :) 🥇 
![Fatal](https://user-images.githubusercontent.com/16899976/92305103-4a549480-ef84-11ea-96eb-ebab24293dc6.PNG)

**Comment by Rav99** [comment]
Its allrdy fixed, pls try the latest github build :)

**Comment by Auxiliotest** [comment]
Excellent, nevermind me then 👍
