### ISSUE TITLE
LUA Error in Aurora since last Update of PTR and Beta Server

### ISSUE THREAD

**Issue by Potsrabe** [liquidbase/DuffedUIv9#19]
Hello, I get this error:

Message: ...Ons\Aurora\Skin\AddOns\Blizzard_ObjectiveTracker.lua:60: attempt to index local 'block' (a nil value)
Time: Thu Sep 10 19:07:04 2020
Count: 5
Stack: ...Ons\Aurora\Skin\AddOns\Blizzard_ObjectiveTracker.lua:60: attempt to index local 'block' (a nil value)
[string "@Interface\AddOns\Aurora\Skin\AddOns\Blizzard_ObjectiveTracker.lua"]:60: in function <...Ons\Aurora\Skin\AddOns\Blizzard_ObjectiveTracker.lua:58>
[string "=[C]"]: in function `GetBlock'
[string "@Interface\AddOns\Blizzard_ObjectiveTracker\Blizzard_BonusObjectiveTracker.lua"]:743: in function <..._ObjectiveTracker\Blizzard_BonusObjectiveTracker.lua:735>
[string "@Interface\AddOns\Blizzard_ObjectiveTracker\Blizzard_BonusObjectiveTracker.lua"]:927: in function <..._ObjectiveTracker\Blizzard_BonusObjectiveTracker.lua:921>
[string "@Interface\AddOns\Blizzard_ObjectiveTracker\Blizzard_BonusObjectiveTracker.lua"]:962: in function `Update'
[string "@Interface\AddOns\Blizzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua"]:1372: in function <...zzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua:1325>
[string "=[C]"]: in function `ObjectiveTracker_Update'
[string "@Interface\AddOns\Blizzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua"]:837: in function <...zzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua:835>

Locals: self = <table> {
 UsesSharedHeader = <function> defined @Interface\AddOns\Blizzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua:171
 contentsHeight = 0
 AddObjective = <function> defined =[C]:-1
 ShowWorldQuests = true
 EndLayout = <function> defined @Interface\AddOns\Blizzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua:150
 rewardsFrame = ObjectiveTrackerWorldQuestRewardsFrame {
 }
 BlocksFrame = ObjectiveTrackerBlocksFrame {
 }
 AddProgressBar = <function> defined =[C]:-1
 GetBlock = <function> defined =[C]:-1
 OnBlockHeaderLeave = <function> defined @Interface\AddOns\Blizzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua:459
 MarkBlocksUnused = <function> defined @Interface\AddOns\Blizzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua:229
 freeLines = <table> {
 }
 FreeUnusedBlocks = <function> defined @Interface\AddOns\Blizzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua:254
 lineTemplate = "BonusObjectiveTrackerLineTemplate"
 Update = <function> defined @Interface\AddOns\Blizzard_ObjectiveTracker\Blizzard_BonusObjectiveTracker.lua:937
 hasSkippedBlocks = false
 AddBlockOffset = <function> defined @Interface\AddOns\Blizzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua:636
 FreeLine = <function> defined @Interface\AddOns\Blizzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua:286
 AddTimerBar = <function> defined =[C]:-1
 FreeBlock = <function> defined @Interface\AddOns\Blizzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua:237
 OnLoad = <function> defined @Interface\AddOns\Blizzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua:97
 buttonOffsets = <table> {
 }
 contentsAnimHeight = 0
 BeginLayout = <function> defined @Interface\AddOns\Blizzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua:131
 SetStringText = <function> defined @Interface\AddOns\Blizzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua:410
 GetBlockCount = <function> defined @Interface\AddOns\Blizzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua:264
 lineWidth = 230
 GetRelatedModules = <function> defined @Interface\AddOns\Blizzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua:594
 SetSharedHeader = <function> defined @Interface\AddOns\Blizzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua:166
 fromModuleOffsetY = -10
 StaticReanchor = <function> defined @Interface\AddOns\Blizzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua:1253
 OnBlockHeaderEnter = <function> defined @Interface\AddOns\Blizzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua:440
 OnBlockHeaderClick = <function> defined @Interface\AddOns\Blizzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua:437
 IsCollapsed = <function> defined @Interface\AddOns\Blizzard_ObjectiveTracker\Blizzard_Object

BR Ralf

**Comment by liquidbase** [comment]
At the moment you have to deactivate Aurora. Blizzard has changed large parts of the quest system frames. We are currently still checking what needs to be changed.

**Comment by liquidbase** [comment]
Please check the issue with the current version here on github.

**Comment by Potsrabe** [comment]
Hello,
I have test it.
Beta Release 9.0.2.35854 - No Errors, works fine
PTR Release 9.0.1.35897 - Same Errors I have posted.

BR Ralf

**Comment by liquidbase** [comment]
Thanks, I know the issue with objectivetracker. Problem are the worldquests here. Fix is under develoopment.

**Comment by liquidbase** [comment]
Issue is fixed with the current version 9.0.2.10. Version can be downloaded here on GitHub, or on wowinterface / curse.

**Comment by Potsrabe** [comment]
Sorry, I have forget to comment. Tetesd and works fine now !

Nice !

Thank You !

BR Ralf
