### ISSUE TITLE
Problems with Aurora backdrop opacity on Beta

### ISSUE THREAD

**Issue by Potsrabe** [liquidbase/DuffedUIv9#21]
Hello,
I have install same Duffed Version 9.0.2 R10 on PTR (from curse over twitch client) and Beta (direct Installation from Github).
On PTR backdrop opacity works on all windows (e.g. Pets), on Beta not on all Windows (e.g. Pets).
Than I have see the following. In the Version from Curse I have XP Bar Right of the Left Chat Frame and it will be moveable. On Beta the XP be will under the action bars and will be not Moveable.

BR Ralf

**Comment by liquidbase** [comment]
Background transparency is currently being checked on the beta server where the error is.
The XP bar should be in the middle under the info panel on the PTR and beta server. That it is no longer movable is what is meant here. See also the commit

**Comment by Potsrabe** [comment]
Hello,
O.K. Thank You for Information. I understand the argument for changing position of XP Bar and Azerith Bar.
Than let us looking forward for the Background transparency.

BR Ralf

**Comment by liquidbase** [comment]
Gave an update for Aurora today.
Please check here whether the problem with the opacity persists or has been resolved. I can't find a problem on the PTR or Beta right now.

**Comment by Potsrabe** [comment]
Hello,
It works, but it needs reload UI to activate the new opacity. (Testted on PTR and Beta)

BR Ralf

**Comment by liquidbase** [comment]
Thanks for the feedback. Then I already know that it works so far. The reload shouldn't be a problem, because you reload the UI during the installation or a configuration change anyway.
