### ISSUE TITLE
Aurora View Error in Calendar

### ISSUE THREAD

**Issue by Potsrabe** [liquidbase/DuffedUIv9#22]
Hello,
I have an view error in calendar with aurora activated. The border arround actual day is to great.

See attachment.

https://www.bilder-upload.eu/bild-d2fff5-1602785142.png.html

BR Ralf

**Comment by liquidbase** [comment]
I will check it.

**Comment by liquidbase** [comment]
Fixed with https://github.com/liquidbase/DuffedUIv9/commit/c49bbcfd53fee23ca8645a7ea335787429a9ff97
