### ISSUE TITLE
Missing Holy Power on Protection Paladin's Class Bar

### ISSUE THREAD

**Issue by Vayreon** [liquidbase/DuffedUIv9#23]
Hello,

when playing with the Protection specialization on my Paladin, the Holy Power display is missing from the class bar. It is present when choosing Ret though.

**Comment by liquidbase** [comment]
Does it only concern the Prot Pala or also Holy?

**Comment by Rav99** [comment]
Blame Rav, i have forgot the old oUF_HolyPowerBar.lua ... :P

**Comment by liquidbase** [comment]
Fixed with commit [ccffd39](https://github.com/liquidbase/DuffedUIv9/commit/ccffd39daf7368ca073f1297a70e316e2f7bb14d)
