### ISSUE TITLE
Cannot open some window from micromenu

### ISSUE THREAD

**Issue by Nem-z** [liquidbase/DuffedUIv9#26]
Hello,

I'm using your addon currently and I have an issue when I try to open some window from the micromenu datatext.

Here are the menus I have a problem with:

- [Specialization & Talents](https://github.com/liquidbase/DuffedUIv9/files/5428956/Specialization.Talents.txt)
- [Player vs Player](https://github.com/liquidbase/DuffedUIv9/files/5428955/Player.vs.Player.txt)
- [Group Finder](https://github.com/liquidbase/DuffedUIv9/files/5428954/Group.Finder.txt)

The window opens without issue if I use keyboard shortcut.

I placed the micromenu in the bottom bar if that can help to track the issue:
![image](https://user-images.githubusercontent.com/63961359/96994880-a4f28180-152d-11eb-974a-5f72fd781d79.png)

Cheers.

Nemz

**Comment by liquidbase** [comment]
Okay I check the issue.

**Comment by liquidbase** [comment]
Errors have been found and a corresponding fix is in progress. In the course of the day there will be a new version.

**Comment by Nem-z** [comment]
Awesome! Thanks.

**Comment by liquidbase** [comment]
Fixed with https://github.com/liquidbase/DuffedUIv9/commit/b00073266bd6700c3e47e6ce23d7b98d30b30d09 and published with version 9.0.2.17
