### ISSUE TITLE
Action Bar / Invisible Overlay?

### ISSUE THREAD

**Issue by Joshosu420** [liquidbase/DuffedUIv9#33]
I have no other addons enabled and this is only on my hunter.  Issue is not present on my shadow priest or warrior.  I am unable to mouseover or click on any buttons on action bar 1 and 2.  However, it is not the entire button, only half the button.  It seems there is an invisible layer / box / field that is covering the button bars.  But I cannot find anything that would cause it.

The yellow box represents an approximate location.  I can click on the top half of bar 1 skills and the bottom half of bar 2 skills.
![WoWScrnShot_110420_170416](https://user-images.githubusercontent.com/20748387/98177627-ae320580-1ec0-11eb-8efb-0615290d5129.jpg)

**Comment by liquidbase** [comment]
The question now is whether this occurs when MoveUI is deactivated or only with MoveUI active. If MoveUI is active, then it is normal that two frames overlap here. In this case it is the movers for Bar1 and Bar2. In addition, Bar2 is a little too high (maybe 3-4px).
In any case, I couldn't understand the problem with myself. All buttons can be used without any problems.
But I take a closer look at it, not that I missed anything.

**Comment by HolySephi** [comment]
@Joshosu420 use /framestack and then your mouse to identify the exact window layers laying above your action bars

**Comment by Joshosu420** [comment]
I will try framestack when I get home.  It is when move-ui is off, during normal play. I can only "see" or click on the skills on the top 1/3rd of bar1 and bottom 1/3rd of bar 2.

**Comment by Joshosu420** [comment]
Okay, /framestack found it.  Its the green box.  That is exactly the outline where I cannot click the action bars.  Next question, how to remove it?  :-)


![WoWScrnShot_110520_171016](https://user-images.githubusercontent.com/20748387/98306661-de91a680-1f89-11eb-8f10-0ab0db6e5aa2.jpg)

**Comment by liquidbase** [comment]
The said frame belongs to the PetActionBar and can only be deactivated if the pet is put away.

I have to check how this can best be fixed, as it is more of a problem with the Blizzard action bars than with the UI. Especially since the UI only modifies the Blizzard action bars in terms of appearance.

**Comment by Joshosu420** [comment]
That has fixed the issue!  Thanks!

**Comment by liquidbase** [comment]
Alright.
Fix will be permanently with r20. For now use the downloaded version from GitHub :)
