### ISSUE TITLE
Bag not working without Pawn Addon

### ISSUE THREAD

**Issue by HolySephi** [liquidbase/DuffedUIv9#35]
Hey,

since the newest update a few hours ago bags are not working anymore if Pawn is not installed. Top right corner is the lua error:
![WoWScrnShot_110520_212505](https://user-images.githubusercontent.com/1346621/98293260-4f4aba00-1fae-11eb-80c7-210686f1cb7c.jpg)

Installing Pawn results in working bags again.

**Comment by liquidbase** [comment]
Download on wowinterface and curse is on approval and on GitHub released

**Comment by liquidbase** [comment]
Fixed with https://github.com/liquidbase/DuffedUIv9/commit/c465cf2fda927723da6f7f8428d73190ff34e1c9
