### ISSUE TITLE
Problem with changing Healthbar color

### ISSUE THREAD

**Issue by kingsteronline** [liquidbase/DuffedUIv9#40]
Hey,

i have problem with Healthbar color. Should be any option to disable class color? If yes, where? Beacuse in Unitframes i dont get it.

Thanks for answer!

![obraz](https://user-images.githubusercontent.com/74932594/100011782-89032980-2dd2-11eb-85ef-b2d3707179f4.png)

**Comment by liquidbase** [comment]
That's not a bug. On top of the section Unit Frames you can found `Show uniform color theme (gray healthbar)`. You can see the option on the screenshot.
![WoWScrnShot_112320_223307](https://user-images.githubusercontent.com/743288/100018369-a3da9b80-2ddc-11eb-8e6b-7acb39508f8b.jpg)
