### ISSUE TITLE
azeritepower modul error

### ISSUE THREAD

**Issue by rush2rio** [liquidbase/DuffedUIv9#41]
I´m getting the below error message really often. I disabled the azeritearmorinformation already in the tooltip option. It seems its appear after i changed my neck item.

`Message: ...erface\AddOns\DuffedUI\modules\misc\azeritepower.lua:52: bad argument #1 to 'C_AzeriteItem_GetAzeriteItemXPInfo' (Usage: local xp, totalLevelXP = C_AzeriteItem.GetAzeriteItemXPInfo(azeriteItemLocation))
Time: Sat Nov 28 17:16:31 2020
Count: 1
Stack: ...erface\AddOns\DuffedUI\modules\misc\azeritepower.lua:52: bad argument #1 to 'C_AzeriteItem_GetAzeriteItemXPInfo' (Usage: local xp, totalLevelXP = C_AzeriteItem.GetAzeriteItemXPInfo(azeriteItemLocation))
[string "=[C]"]: ?
[string "@Interface\AddOns\DuffedUI\modules\misc\azeritepower.lua"]:52: in function <...erface\AddOns\DuffedUI\modules\misc\azeritepower.lua:38>

Locals: (*temporary) = <table> {
 GetBagAndSlot = <function> defined @Interface\FrameXML\ObjectAPI\ItemLocation.lua:34
 IsBagAndSlot = <function> defined @Interface\FrameXML\ObjectAPI\ItemLocation.lua:52
 SetEquipmentSlot = <function> defined @Interface\FrameXML\ObjectAPI\ItemLocation.lua:38
 HasAnyLocation = <function> defined @Interface\FrameXML\ObjectAPI\ItemLocation.lua:56
 Clear = <function> defined @Interface\FrameXML\ObjectAPI\ItemLocation.lua:21
 IsEquipmentSlot = <function> defined @Interface\FrameXML\ObjectAPI\ItemLocation.lua:48
 IsEqualToBagAndSlot = <function> defined @Interface\FrameXML\ObjectAPI\ItemLocation.lua:64
 SetBagAndSlot = <function> defined @Interface\FrameXML\ObjectAPI\ItemLocation.lua:27
 IsEqualTo = <function> defined @Interface\FrameXML\ObjectAPI\ItemLocation.lua:80
 GetEquipmentSlot = <function> defined @Interface\FrameXML\ObjectAPI\ItemLocation.lua:44
 IsEqualToEquipmentSlot = <function> defined @Interface\FrameXML\ObjectAPI\ItemLocation.lua:72
 slotIndex = 21
 bagID = 6
 IsValid = <function> defined @Interface\FrameXML\ObjectAPI\ItemLocation.lua:60
}
`

Thanks for the great work!

KR

**Comment by liquidbase** [comment]
What level does the character have? Normally the Azerite system deactivates automatically from level 51.

But will check with a twink where the error is exactly.

**Comment by rush2rio** [comment]
Its max level lvl 60 now. Its getting really annoying now. After every drop or equip some new items or loadingscreen

**Comment by liquidbase** [comment]
Please check with this version if the issue persist => https://github.com/liquidbase/DuffedUIv9/archive/master.zip
If not the fix is permanent for the next version.

**Comment by rush2rio** [comment]
yes its fixed! Thanks!
