### ISSUE TITLE
Covenant map button missing

### ISSUE THREAD

**Issue by NeriCasados** [liquidbase/DuffedUIv9#52]
I've been playing around with the UI, but can't seem to find the Covenant button that's usually on top of the map in normal WoW UI.

On another note, I restored the chat's config to the Blizzard default's one and can't go back to the way DuffedUI has it when you first install, is there any way to reset chat?

**Comment by liquidbase** [comment]
You can find the button for the covenants in the minimap menu. The menu can be reached by mouse wheel click or Shift+right click in the minimap. The point here is then called the Garrison Report.

For the chat it is enough to simply re-read the script via /install. An additional command will be added here in the next version.
